Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Fig1()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-5-4605d7ee72f8>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mFig1[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-4-f005c3a2be12>[0m in [0;36mFig1[0;34m(beta, rho)[0m
[1;32m      2[0m     [0mcC[0m [0;34m=[0m [0mContract[0m[0;34m.[0m[0mCompetitive[0m[0;34m([0m[0mbeta[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mcC[0m[0;34m.[0m[0mrho[0m [0;34m=[0m [0mrho[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mFigure1[0m[0;34m([0m[0mcC[0m[0;34m,[0m [0midl[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-3-9637810c394a>[0m in [0;36mFigure1[0;34m(cC, idl)[0m
[1;32m      2[0m     [0mcCF[0m [0;34m=[0m [0mcC[0m[0;34m.[0m[0mfcommit[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mcCRP[0m [0;34m=[0m [0mcC[0m[0;34m.[0m[0mreneg[0m[0;34m([0m[0mcCF[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mcCP[0m [0;34m=[0m [0mcC[0m[0;34m.[0m[0mcreneg[0m[0;34m([0m[0mcCF[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m     [0mprint[0m[0;34m([0m[0mcC[0m[0;34m.[0m[0mownsmooth[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m     [0my[0m [0;34m=[0m [0mcC[0m[0;34m.[0m[0my[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'Competitive' object has no attribute 'creneg'
AttributeError: 'Competitive' object has no attribute 'creneg'

